services:
  db:
    build:
      context: ./docker/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ChatBot
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  python-api:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
        - .env
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

